// This file contains health tips and recommendations that can be generated by the chatbot

export interface HealthTip {
    category: string
    title: string
    content: string
  }
  
  export const healthTips: HealthTip[] = [
    {
      category: "nutrition",
      title: "Balanced Diet",
      content:
        "A balanced diet should include fruits, vegetables, whole grains, lean proteins, and healthy fats. Aim for at least 5 servings of fruits and vegetables daily to get essential vitamins and minerals.",
    },
    {
      category: "nutrition",
      title: "Hydration",
      content:
        "Drink at least 8 glasses (about 2 liters) of water daily. Proper hydration helps maintain body temperature, lubricates joints, and helps transport nutrients to give you energy and keep you healthy.",
    },
    {
      category: "nutrition",
      title: "Protein Intake",
      content:
        "Include protein-rich foods like pulses, dairy, eggs, fish, or lean meat in your diet. Protein is essential for building and repairing tissues and making enzymes and hormones.",
    },
    {
      category: "exercise",
      title: "Regular Physical Activity",
      content:
        "Aim for at least 150 minutes of moderate-intensity exercise per week. This can include brisk walking, cycling, swimming, or any activity that increases your heart rate.",
    },
    {
      category: "exercise",
      title: "Strength Training",
      content:
        "Include strength training exercises at least twice a week. This helps maintain muscle mass, bone density, and improves overall metabolism.",
    },
    {
      category: "exercise",
      title: "Flexibility and Balance",
      content:
        "Practice yoga or simple stretching exercises to improve flexibility and balance, which becomes increasingly important as you age.",
    },
    {
      category: "sleep",
      title: "Sleep Hygiene",
      content:
        "Aim for 7-9 hours of quality sleep each night. Maintain a regular sleep schedule, create a restful environment, and avoid screens before bedtime.",
    },
    {
      category: "sleep",
      title: "Sleep Environment",
      content:
        "Keep your bedroom cool, quiet, and dark. Use comfortable bedding and consider using earplugs, an eye mask, or white noise machine if needed.",
    },
    {
      category: "mental_health",
      title: "Stress Management",
      content:
        "Practice stress-reduction techniques such as deep breathing, meditation, or progressive muscle relaxation. Regular practice can help manage stress and improve mental well-being.",
    },
    {
      category: "mental_health",
      title: "Social Connections",
      content:
        "Maintain social connections with family, friends, and community. Strong social ties are linked to better health outcomes and longevity.",
    },
    {
      category: "mental_health",
      title: "Mindfulness Practice",
      content:
        "Practice mindfulness by focusing on the present moment without judgment. This can reduce anxiety, depression, and improve overall mental health.",
    },
    {
      category: "preventive_care",
      title: "Regular Health Check-ups",
      content:
        "Schedule regular health check-ups and screenings as recommended by your healthcare provider. Early detection of health issues can lead to more effective treatment.",
    },
    {
      category: "preventive_care",
      title: "Vaccination",
      content:
        "Stay up-to-date with recommended vaccinations. Vaccines help protect against serious and potentially life-threatening diseases.",
    },
    {
      category: "preventive_care",
      title: "Dental Care",
      content:
        "Brush your teeth twice daily, floss regularly, and visit your dentist for check-ups every six months. Good oral hygiene is linked to overall health.",
    },
    {
      category: "women_health",
      title: "Prenatal Care",
      content:
        "If pregnant, attend all scheduled prenatal check-ups. Good prenatal care is essential for the health of both mother and baby.",
    },
    {
      category: "women_health",
      title: "Breast Self-Examination",
      content:
        "Perform monthly breast self-examinations and schedule regular mammograms as recommended by your healthcare provider.",
    },
    {
      category: "women_health",
      title: "Iron-Rich Diet",
      content:
        "Women, especially those of reproductive age, should ensure adequate iron intake through diet or supplements to prevent anemia.",
    },
    {
      category: "child_health",
      title: "Immunization",
      content:
        "Ensure children receive all recommended vaccinations on schedule. Immunizations protect children from serious and potentially fatal diseases.",
    },
    {
      category: "child_health",
      title: "Growth Monitoring",
      content:
        "Regularly monitor your child's growth and development. Consult with a healthcare provider if you notice any concerns.",
    },
    {
      category: "child_health",
      title: "Nutritious Diet",
      content:
        "Provide children with a balanced diet rich in fruits, vegetables, whole grains, and proteins to support their growth and development.",
    },
    {
      category: "elderly_health",
      title: "Fall Prevention",
      content:
        "Make home modifications to prevent falls, such as removing tripping hazards, improving lighting, and installing grab bars in bathrooms.",
    },
    {
      category: "elderly_health",
      title: "Cognitive Stimulation",
      content:
        "Engage in activities that stimulate the mind, such as reading, puzzles, or learning new skills, to maintain cognitive function.",
    },
    {
      category: "elderly_health",
      title: "Medication Management",
      content:
        "Keep track of medications, take them as prescribed, and regularly review them with your healthcare provider to avoid adverse interactions.",
    },
    {
      category: "chronic_disease",
      title: "Diabetes Management",
      content:
        "If you have diabetes, monitor your blood sugar levels regularly, take medications as prescribed, maintain a healthy diet, and exercise regularly.",
    },
    {
      category: "chronic_disease",
      title: "Hypertension Control",
      content:
        "If you have high blood pressure, monitor it regularly, take medications as prescribed, reduce salt intake, maintain a healthy weight, and exercise regularly.",
    },
    {
      category: "chronic_disease",
      title: "Heart Health",
      content:
        "Maintain heart health by eating a heart-healthy diet, exercising regularly, not smoking, limiting alcohol, and managing stress.",
    },
  ]
  
  export function getHealthTipsByCategory(category: string): HealthTip[] {
    return healthTips.filter((tip) => tip.category === category)
  }
  
  export function getRandomHealthTip(): HealthTip {
    const randomIndex = Math.floor(Math.random() * healthTips.length)
    return healthTips[randomIndex]
  }
  
  export function getHealthTipsByKeyword(keyword: string): HealthTip[] {
    const lowerKeyword = keyword.toLowerCase()
    return healthTips.filter(
      (tip) =>
        tip.category.toLowerCase().includes(lowerKeyword) ||
        tip.title.toLowerCase().includes(lowerKeyword) ||
        tip.content.toLowerCase().includes(lowerKeyword),
    )
  }
  
  export function generateHealthRecommendation(issue: string): string {
    // Map common health issues to appropriate categories
    const issueMap: Record<string, string> = {
      // Nutrition related
      diet: "nutrition",
      food: "nutrition",
      eating: "nutrition",
      weight: "nutrition",
      nutrition: "nutrition",
      hydration: "nutrition",
      water: "nutrition",
  
      // Exercise related
      exercise: "exercise",
      fitness: "exercise",
      workout: "exercise",
      "physical activity": "exercise",
      strength: "exercise",
      flexibility: "exercise",
  
      // Sleep related
      sleep: "sleep",
      insomnia: "sleep",
      rest: "sleep",
      tired: "sleep",
      fatigue: "sleep",
  
      // Mental health related
      stress: "mental_health",
      anxiety: "mental_health",
      depression: "mental_health",
      mental: "mental_health",
      mood: "mental_health",
      emotion: "mental_health",
  
      // Preventive care related
      "check-up": "preventive_care",
      checkup: "preventive_care",
      screening: "preventive_care",
      prevention: "preventive_care",
      vaccine: "preventive_care",
      vaccination: "preventive_care",
      dental: "preventive_care",
  
      // Women's health related
      pregnancy: "women_health",
      prenatal: "women_health",
      breast: "women_health",
      menstruation: "women_health",
      menopause: "women_health",
  
      // Child health related
      child: "child_health",
      baby: "child_health",
      infant: "child_health",
      toddler: "child_health",
      kid: "child_health",
      children: "child_health",
  
      // Elderly health related
      elderly: "elderly_health",
      senior: "elderly_health",
      aging: "elderly_health",
      "old age": "elderly_health",
  
      // Chronic disease related
      diabetes: "chronic_disease",
      hypertension: "chronic_disease",
      "blood pressure": "chronic_disease",
      heart: "chronic_disease",
      cholesterol: "chronic_disease",
      chronic: "chronic_disease",
    }
  
    // Find matching category for the issue
    const lowerIssue = issue.toLowerCase()
    let category = "general"
  
    for (const [key, value] of Object.entries(issueMap)) {
      if (lowerIssue.includes(key)) {
        category = value
        break
      }
    }
  
    // Get tips for the category
    const tips =
      category === "general"
        ? [getRandomHealthTip(), getRandomHealthTip(), getRandomHealthTip()]
        : getHealthTipsByCategory(category)
  
    // If no specific tips found, get random tips
    const selectedTips =
      tips.length > 0
        ? tips.slice(0, Math.min(3, tips.length))
        : [getRandomHealthTip(), getRandomHealthTip(), getRandomHealthTip()]
  
    // Generate recommendation text
    let recommendation = `Here are some health recommendations regarding ${issue}:\n\n`
  
    selectedTips.forEach((tip, index) => {
      recommendation += `${index + 1}. **${tip.title}**: ${tip.content}\n\n`
    })
  
    recommendation +=
      "Remember, these are general recommendations. For specific medical advice, please consult a healthcare professional."
  
    return recommendation
  }
  